// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBurSfKjJVqj9GDX88U7VskXCZ8SgLjhVg',
    appId: '1:464573984927:web:0782649e497c3dd776f2aa',
    messagingSenderId: '464573984927',
    projectId: 'flutter-login-32920',
    authDomain: 'flutter-login-32920.firebaseapp.com',
    storageBucket: 'flutter-login-32920.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9tdUGsD34QAz3f9j9dg9Nzk2kHAWShxg',
    appId: '1:464573984927:android:fbdbcc264a0d9bb576f2aa',
    messagingSenderId: '464573984927',
    projectId: 'flutter-login-32920',
    storageBucket: 'flutter-login-32920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3PtfmaB7tFR1wJIfQwgTqZCIwLCXmK98',
    appId: '1:464573984927:ios:d6309527ab93fa3e76f2aa',
    messagingSenderId: '464573984927',
    projectId: 'flutter-login-32920',
    storageBucket: 'flutter-login-32920.appspot.com',
    iosBundleId: 'com.example.flutterAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3PtfmaB7tFR1wJIfQwgTqZCIwLCXmK98',
    appId: '1:464573984927:ios:45df50013bee154776f2aa',
    messagingSenderId: '464573984927',
    projectId: 'flutter-login-32920',
    storageBucket: 'flutter-login-32920.appspot.com',
    iosBundleId: 'com.example.flutterAppTest.RunnerTests',
  );
}
